name: Bug Report
description: Report a bug or issue with Factur-X Express
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: bug-area
    attributes:
      label: Bug Area
      description: Which area of the application is affected?
      options:
        - Invoice Generation
        - PDF/A-3 Processing
        - Factur-X/XML Handling
        - User Interface
        - API/Backend
        - Authentication
        - Validation (veraPDF/Mustangproject)
        - File Upload/Download
        - Database
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Major functionality broken
        - Critical - Application unusable or data loss
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g. macOS 14.0, Ubuntu 24.04]
        - Browser: [e.g. Chrome 120, Safari 17]
        - Node.js version: [e.g. 20.10.0]
        - Python version: [e.g. 3.11.6]
        - Docker version: [if applicable]
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please include any relevant error messages or logs
      placeholder: Paste error logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: invoice-data
    attributes:
      label: Invoice Data (if applicable)
      description: If the bug is related to invoice processing, please provide sample data (remove sensitive information)
      placeholder: |
        {
          "invoice_number": "FX-2024-001",
          "amount": 100.00,
          "currency": "EUR",
          ...
        }
      render: json
    validations:
      required: false

  - type: textarea
    id: validation-reports
    attributes:
      label: Validation Reports (if applicable)
      description: If the bug involves validation failures, please include the validation reports
      placeholder: Paste validation reports here...
      render: json
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Files
      description: If applicable, add screenshots or attach files to help explain the problem
      placeholder: Drag and drop files here or paste screenshots...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: compliance-impact
    attributes:
      label: Compliance Impact
      description: Does this bug affect compliance requirements?
      options:
        - label: Affects EN 16931 compliance
        - label: Affects PDF/A-3 standards
        - label: Affects Factur-X validation
        - label: Affects French fiscal requirements
        - label: Security vulnerability

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true
        - label: I have included relevant error messages and logs
          required: true
        - label: I have removed any sensitive information from the report
          required: true